"""add description timestamp

Revision ID: 005384986541
Revises: 2519759ddb21
Create Date: 2025-10-05 01:09:09.939809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005384986541'
down_revision = '2519759ddb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politician', schema=None) as batch_op:
        batch_op.drop_column('description_generated_at')

    # ### end Alembic commands ###
